
project_id = "ygohnbvouslbasrtrbxa"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327

[auth]
enabled = true
port = 54328

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.create-stripe-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.check-subscription-status]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true
