// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvpvirrvrrypmgljkaue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2cHZpcnJ2cnJ5cG1nbGprYXVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2Mzc1ODQsImV4cCI6MjA2MjIxMzU4NH0.3ihUAZGb6OGiwRLfCqEI3vBr2476uY2IJrsNe1QWoQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);